### ISSUE TITLE
[REQUEST] Show minimap when the code is selected.

### ISSUE THREAD

**Issue by tesseslol** [ansballard/minimap-autohider#1]
Can you add this features?

**Comment by ansballard** [comment]
That seems reasonable to me. Since the current version is just listening for scroll events and kicking off a timer, it shouldn't be too difficult to just listen for click events on the editor as well. I think I would keep the default to just opening on scroll though, and add an option for listening for clicks on the settings page.

**Comment by ansballard** [comment]
This should be working in 1.5.1! Sorry for the wait, this kind of fell off my radar, and I only caught it when someone requested a similar feature. Hope it works for you!
