### ISSUE TITLE
Minimap Absolute mode

### ISSUE THREAD

**Issue by balderclaassen** [ansballard/minimap-autohider#10]
The Minimap extension has a checkbox for "Absolute Mode" which defaults to false 
In minimap-autohider it seems true is the default and unchangeable; not affected by the Absolute mode checkbox. In other words, with this extension I can't let the minimap take up its own space.

Is this by design or a bug ?

**Comment by ansballard** [comment]
By design. The original plugin I forked from only used absolute mode, so that's what I went with. I did look into adding support for non-absolute mode, but it looked like it would take a lot of effort to get the entire window to shift over correctly whenever the minimap is hidden. If you can find a way to get it working, I'd love to look at it and merge it in!

**Comment by balderclaassen** [comment]
Thanks for the clarification :+1: 
I don't know much about atom packages code so if you already mention it seemed difficult I doubt I will be able to at the moment ;) 
Anyways I realized that now that the minimap hides properly, because of this extension, I don't really prefer "absolute mode" anymore. I didn't want it to cover my code because it was always visible. But since it auto-hides having the windows not shift is actually better. 
As far as I am concerned you can close this. 
Thank you :)
